pipeline{
    agent{
        label 'Agent 1'
    }
    options{
        timeout(time: 30, unit: 'MINUTES')
        disableConcurrentBuilds()4
    }
    parameters{

    }
    environment{

    }
    stages{
        stage('Build'){
            steps{
                sh 'echo this is build'
            }
        }
        stage('Test'){
            steps{
                sh 'echo this is test'
            }
        }
        stage('Deploy'){
            steps{
                sh 'echo this is deploy'
            }
        }
        stage('Print Parameters'){
            steps{

            }
        }
    }

    post{
        always { 
            echo 'I will always say Hello again!'
        }
        success { 
            echo 'I will run when pipeline is success'
        }
        failure { 
            echo 'I will run when pipeline is failure'
        }
    }
}